---

#Override default image
#aws_image: "{{ aws_image}}"

#   Cloud Formation Stack Name
stack_name: "myservers"

# SSH Keypair for the instance
# aws_key_name: "ansible"

#Establish server hostname
server_name: "server01.ansiblelab.com"
server_name2: "server02.ansiblelab.com"

#Type of AWS instance
aws_instancetype: "t2.micro"

#Establish  server subnets
subnet: subnet-0931e29ed7d40ff69
subnet2: subnet-034aa9fa4cfbffa1d

# Establish EBS Encryption key
# ebs_key: "ff01e1f8-edfa-44d6-b511-3fc07445765c"


# Establish private Route53 DNS zone
private_hosted_zone: Z05054631J16XLH4YQJ0B

# Establish VPC
vpc_id: vpc-013ddcbef4a15b7f5

#Disks to attach to instance
disks:
  - name: "root_volume"
    type: "gp2"
    size: "8"
    device_name: "/dev/xvda"
